spring.application.name=cloudshare
#spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/cloudshare?directConnection=true&serverSelectionTimeoutMS=5000


spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare

server.servlet.context-path=/api/v1
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
clerk.issuer=https://advanced-mosquito-50.clerk.accounts.dev
clerk.jwks-url=https://advanced-mosquito-50.clerk.accounts.dev/.well-known/jwks.json