spring.application.name=cloudshare
#spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/cloudshare?directConnection=true&serverSelectionTimeoutMS=5000


spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare

server.servlet.context-path=/api/v1
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
clerk.issuer=
clerk.jwks-url=
clerk.webhook.secret=